FROM node:24-alpine AS base
WORKDIR /usr/src/app
COPY package.json package-lock.json* ./
RUN npm install --omit=dev

FROM node:24-alpine
WORKDIR /usr/src/app
COPY --from=base /usr/src/app/node_modules ./node_modules
COPY . .
ENV PORT=3000
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1
CMD ["node", "index.js"]
